{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meilisearch-proxy.fullname" . }}-secret
  labels:
    app: {{ include "meilisearch-proxy.name" . }}
    chart: {{ include "meilisearch-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  MEILISEARCH_HOST: {{ .Values.meilisearch.url | b64enc | quote }}
  MEILISEARCH_MASTER_KEY: {{ "" | b64enc | quote }}
  PROXY_MASTER_KEY_OVERRIDE: {{ .Values.proxy.overrideProxyKey | quote | b64enc | quote }}
  PROXY_MASTER_KEY: {{ "" | b64enc | quote }}
  MEILISEARCH_PUBLIC_KEY_OVERRIDE: {{ "true" | b64enc | quote }}
  CACHE_ENGINE: {{ .Values.proxy.cacheEngine | b64enc | quote }}
  CACHE_URL: {{ .Values.proxy.masterKey | b64enc | quote }}
  CACHE_TTL: {{ .Values.proxy.cacheDuration | b64enc | quote }}
  PORT: {{ .Values.proxy.port | b64enc | quote }}
  LOG_LEVEL: {{ .Values.proxy.logLevel | b64enc | quote }}
  PROXY_PURGE_TOKEN: {{ .Values.proxy.purgeToken | b64enc | quote }}
  AUTO_RESTART_INTERVAL: {{ .Values.proxy.autoRestartInterval | b64enc | quote }}
{{- end }}
