name: Build and Deploy

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: meilisearch-proxy
  FULL_IMAGE: registry.maxroll.gg/library/meilisearch-proxy

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go 1.22.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.22.x'

      - name: Install dependencies
        run: |
          go mod download

      - name: Install Ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Run tests
        run: |
          ginkgo -r -v

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - name: echo environment
        run: |
          echo "Environment: ${{ vars.ENV }}"
          echo "Image name: ${{ env.FULL_IMAGE }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.FULL_IMAGE }}
          tags: |
            type=raw,value=latest,enable=true
            type=semver,pattern={{version}}
            type=sha
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.maxroll.gg
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v6
        with:
          build-args: GITHUB_PACKAGE_TOKEN=${{ secrets.GITHUB_TOKEN }}
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Package Helm chart
        run: helm package charts/meilisearch-proxy

      - name: Login to Helm registry
        run: helm registry login -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }} https://registry.maxroll.gg

      - name: Push Helm chart to registry
        run: helm registry push *.tgz registry.maxroll.gg